development:
  adapter: "postgis"
  encoding: "utf8"
  database: "groupgeo_development"
  pool: "5"
  username: "groupgeo"
  password: "groupgeo"
  host: "127.0.0.1"
  port: "5432"

test:
  adapter: "postgis"
  encoding: "utf8"
  database: "groupgeo_test"
  pool: "5"
  username: "groupgeo"
  password: "groupgeo"
  host: "127.0.0.1"
  port: "5432"